//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karamem0.SharePoint.PowerShell.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Karamem0.SharePoint.PowerShell.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access token has expired, please login again.
        /// </summary>
        public static string ErrorAccessTokenExpired {
            get {
                return ResourceManager.GetString("ErrorAccessTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The access token is not cached, please login again.
        /// </summary>
        public static string ErrorAccessTokenIsNotCached {
            get {
                return ResourceManager.GetString("ErrorAccessTokenIsNotCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve Tenant ID from resource URL.
        /// </summary>
        public static string ErrorCannotResolveTenantId {
            get {
                return ResourceManager.GetString("ErrorCannotResolveTenantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max retry count exceeded.
        /// </summary>
        public static string ErrorMaxRetryCountExceeded {
            get {
                return ResourceManager.GetString("ErrorMaxRetryCountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected to SharePoint Server.
        /// </summary>
        public static string ErrorNotConnected {
            get {
                return ResourceManager.GetString("ErrorNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation timed out.
        /// </summary>
        public static string ErrorOperationTimeout {
            get {
                return ResourceManager.GetString("ErrorOperationTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be less than &apos;{0}&apos;.
        /// </summary>
        public static string ErrorValueCannotBeLessThan {
            get {
                return ResourceManager.GetString("ErrorValueCannotBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be more than &apos;{0}&apos;.
        /// </summary>
        public static string ErrorValueCannotBeMoreThan {
            get {
                return ResourceManager.GetString("ErrorValueCannotBeMoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be null.
        /// </summary>
        public static string ErrorValueCannotBeNull {
            get {
                return ResourceManager.GetString("ErrorValueCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be &apos;{0}&apos;.
        /// </summary>
        public static string ErrorValueCannotBeValue {
            get {
                return ResourceManager.GetString("ErrorValueCannotBeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is invalid.
        /// </summary>
        public static string ErrorValueIsInvalid {
            get {
                return ResourceManager.GetString("ErrorValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a absolute URL.
        /// </summary>
        public static string ErrorValueIsNotAbsoluteUrl {
            get {
                return ResourceManager.GetString("ErrorValueIsNotAbsoluteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a relative URL.
        /// </summary>
        public static string ErrorValueIsNotRelativeUrl {
            get {
                return ResourceManager.GetString("ErrorValueIsNotRelativeUrl", resourceCulture);
            }
        }
    }
}
