name: Deploy to GitHub Release

description: This GitHub Action deploys built artifacts to GitHub Release.

runs:
  using: composite
  steps:
    - name: Download artifacts
      uses: actions/download-artifact@v8
      with:
        name: build
        path: build
    - name: Archive artifacts
      shell: pwsh
      run: Compress-Archive -Path build/* -DestinationPath ${{env.RELEASE_FILE_NAME}}
    - name: Create release
      uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda
      env:
        GITHUB_TOKEN: ${{env.GITHUB_TOKEN}}
      with:
        files: ${{env.RELEASE_FILE_NAME}}
