name: Deploy to GitHub Packages

on: workflow_call

permissions:
  packages: write

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build/SPClientCore
      - name: Publish to GitHub Packages
        shell: pwsh
        run: |
          $username = "${{github.repository_owner}}"
          $password = ConvertTo-SecureString "${{secrets.GITHUB_TOKEN}}" -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential -ArgumentList $username, $password
          Register-PSRepository `
            -Name GitHub `
            -SourceLocation "https://nuget.pkg.github.com/${{github.repository_owner}}/index.json" `
            -PublishLocation "https://nuget.pkg.github.com/${{github.repository_owner}}/index.json" `
            -Credential $credential
          Publish-Module `
            -Path "${{github.workspace}}/build/SPClientCore" `
            -Repository "GitHub" `
            -NugetApiKey "${{secrets.GITHUB_TOKEN}}"
