on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
  publish:
    name: Publish
    needs: build
    uses: ./.github/workflows/publish.yml
    secrets: inherit
  release:
    name: Release
    needs: build
    uses: ./.github/workflows/release.yml
    secrets: inherit
