name: Trigger on develop

on:
  push:
    branches:
      - develop

permissions:
  checks: write

jobs:
  test-source:
    name: Test source
    uses: ./.github/workflows/test-source.yml
    secrets: inherit
  build-source:
    name: Build source
    needs: test-source
    uses: ./.github/workflows/build-source.yml
    secrets: inherit
